server:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"

  config:
    persistence:
      default:
        driver: "" # cassandra or sql

        cassandra:
          hosts: []
          # port: 9042
          keyspace: cadence
          consistency: One
          user: ""
          password: ""

        sql:
          pluginName: "" # mysql
          host: ""
          # port: 3306
          database: cadence
          user: ""
          password: ""
          encodingType: "thriftrw" # Note: required only until 0.18.0.
          decodingTypes: ["thriftrw"] # Note: required only until 0.18.0.

      visibility:
        driver: "" # cassandra or sql

        cassandra:
          hosts: []
          # port: 9042
          keyspace: cadence_visibility
          consistency: One
          user: ""
          password: ""

        sql:
          pluginName: "" # mysql
          host: ""
          # port: 3306
          database: cadence_visibility
          user: ""
          password: ""
          encodingType: "thriftrw" # Note: required only until 0.18.0.
          decodingTypes: ["thriftrw"] # Note: required only until 0.18.0.

schema:
  setup: false
  update: false

cassandra:
  enabled: false

mysql:
  enabled: false
